import React,{useMemo,useState} from 'react';
import { SaleRecord,InventoryItem } from '../types';
import { DollarSign,Plus,ReceiptText,TrendingUp,Coins,Percent,X,Pencil,Trash2 } from 'lucide-react';
type Draft=Partial<SaleRecord>&{inventoryId:string;quantity:number;source:'LOCAL'|'FULL';salePriceUnit:number;receivedAmount:number;soldAt:string;extraCosts:number};
const today=()=>new Date().toISOString().slice(0,10);
export const FinanceView:React.FC<{sales:SaleRecord[];items:InventoryItem[];onSave:(d:Draft)=>Promise<void>;onDelete:(id:string)=>Promise<void>}>=({sales,items,onSave,onDelete})=>{
 const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[period,setPeriod]=useState('30'),[draft,setDraft]=useState<Draft>({inventoryId:'',quantity:1,source:'FULL',salePriceUnit:0,receivedAmount:0,soldAt:today(),extraCosts:0});
 const filtered=useMemo(()=>{if(period==='all')return sales;const days=Number(period),cut=new Date();cut.setDate(cut.getDate()-days);return sales.filter(s=>new Date(s.soldAt+'T23:59:59')>=cut)},[sales,period]);
 const stats=useMemo(()=>{const gross=filtered.reduce((a,s)=>a+s.salePriceUnit*s.quantity,0),received=filtered.reduce((a,s)=>a+s.receivedAmount,0),cmv=filtered.reduce((a,s)=>a+s.cmv,0),extra=filtered.reduce((a,s)=>a+s.extraCosts,0),profit=received-cmv-extra,units=filtered.reduce((a,s)=>a+s.quantity,0);return{gross,received,cmv,extra,profit,margin:received?profit/received*100:0,ticket:filtered.length?gross/filtered.length:0,units}},[filtered]);
 const add=()=>{setDraft({inventoryId:items[0]?.id||'',quantity:1,source:'FULL',salePriceUnit:0,receivedAmount:0,soldAt:today(),extraCosts:0});setOpen(true)};
 const edit=(s:SaleRecord)=>{setDraft({...s});setOpen(true)};
 const num=(x:string)=>Math.max(0,Number(x)||0);
 const submit=async()=>{if(!draft.inventoryId)return;setSaving(true);try{await onSave(draft);setOpen(false)}finally{setSaving(false)}};
 const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 return <div className="space-y-5 max-w-[1500px] mx-auto">
  <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><div className="flex items-center gap-2"><DollarSign className="w-6 h-6 text-amber-500"/><h1 className="text-2xl font-black">Financeiro & Vendas</h1></div><p className="text-sm text-slate-500 mt-1">Mini ERP financeiro integrado aos SKUs e ao estoque.</p></div><div className="flex gap-2"><select value={period} onChange={e=>setPeriod(e.target.value)} className="rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 px-3 py-2 text-sm"><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option><option value="all">Todo período</option></select><button onClick={add} disabled={!items.length} className="rounded-xl bg-amber-400 disabled:opacity-50 text-slate-950 font-black px-4 py-2 text-sm flex items-center gap-2"><Plus className="w-4 h-4"/>Nova venda</button></div></div>
  <div className="grid grid-cols-2 lg:grid-cols-4 xl:grid-cols-7 gap-3">{[['Faturamento',money(stats.gross),ReceiptText],['Recebido',money(stats.received),Coins],['CMV',money(stats.cmv),Coins],['Outros custos',money(stats.extra),Coins],['Lucro líquido',money(stats.profit),TrendingUp],['Margem',`${stats.margin.toFixed(1)}%`,Percent],['Ticket médio',money(stats.ticket),ReceiptText]].map(([l,v,I]:any)=><div key={l} className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-4"><div className="text-2xs uppercase font-bold text-slate-500 flex gap-1.5 items-center"><I className="w-3.5 h-3.5"/>{l}</div><div className="font-black mt-2 text-lg">{v}</div></div>)}</div>
  <section className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-hidden"><div className="p-4 border-b border-slate-200 dark:border-slate-800"><h2 className="font-black">Todas as vendas</h2><p className="text-xs text-slate-500">Preço e valor recebido ficam gravados por venda e podem ser editados individualmente.</p></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[1150px] text-xs"><thead className="bg-slate-50 dark:bg-slate-800/70 text-slate-500"><tr>{['Data','Pedido','SKU / Produto','Qtd.','Origem','Preço venda','Recebido','CMV','Custos','Lucro','Margem',''].map(x=><th key={x} className="text-left p-3 font-black uppercase">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{filtered.map(s=>{const gross=s.salePriceUnit*s.quantity,profit=s.receivedAmount-s.cmv-s.extraCosts,margin=s.receivedAmount?profit/s.receivedAmount*100:0;return <tr key={s.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/40"><td className="p-3">{new Date(s.soldAt+'T12:00:00').toLocaleDateString('pt-BR')}</td><td className="p-3">{s.orderNumber||'—'}</td><td className="p-3"><b className="text-amber-600">{s.sku}</b><div className="font-semibold">{s.productName}</div></td><td className="p-3 font-bold">{s.quantity}</td><td className="p-3">{s.source}</td><td className="p-3 font-bold">{money(gross)}</td><td className="p-3 font-bold">{money(s.receivedAmount)}</td><td className="p-3">{money(s.cmv)}</td><td className="p-3">{money(s.extraCosts)}</td><td className={`p-3 font-black ${profit>=0?'text-emerald-600':'text-rose-600'}`}>{money(profit)}</td><td className="p-3 font-bold">{margin.toFixed(1)}%</td><td className="p-3"><div className="flex"><button onClick={()=>edit(s)} className="p-2 hover:text-amber-600"><Pencil className="w-4 h-4"/></button><button onClick={()=>confirm('Excluir esta venda? O estoque será devolvido automaticamente.')&&onDelete(s.id)} className="p-2 hover:text-rose-600"><Trash2 className="w-4 h-4"/></button></div></td></tr>})}</tbody></table>{!filtered.length&&<div className="p-10 text-center text-slate-500">Nenhuma venda neste período.</div>}</div>
  </section>
  {open&&<div className="fixed inset-0 z-[90] bg-slate-950/75 p-3 grid place-items-center"><div className="w-full max-w-2xl max-h-[92vh] overflow-y-auto rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800"><div className="p-4 border-b border-slate-200 dark:border-slate-800 flex justify-between"><div><h2 className="font-black">{draft.id?'Editar venda':'Registrar venda'}</h2><p className="text-xs text-slate-500">O custo do SKU é congelado no momento da primeira gravação.</p></div><button onClick={()=>setOpen(false)}><X className="w-5 h-5"/></button></div><div className="p-5 space-y-4">
   <div className="grid sm:grid-cols-2 gap-3"><label className="text-xs font-bold">SKU<select value={draft.inventoryId} onChange={e=>setDraft({...draft,inventoryId:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 px-3 py-3">{items.map(i=><option key={i.id} value={i.id}>{i.sku} — {i.name}</option>)}</select></label><label className="text-xs font-bold">Nº pedido<input value={draft.orderNumber||''} onChange={e=>setDraft({...draft,orderNumber:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-3"/></label></div>
   <div className="grid grid-cols-2 sm:grid-cols-3 gap-3"><label className="text-xs font-bold">Data<input type="date" value={draft.soldAt} onChange={e=>setDraft({...draft,soldAt:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-3"/></label><label className="text-xs font-bold">Quantidade<input type="number" min="1" value={draft.quantity} onChange={e=>setDraft({...draft,quantity:Math.max(1,Math.floor(num(e.target.value)))})} className="mt-1 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-3"/></label><label className="text-xs font-bold">Origem<select value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value as any})} className="mt-1 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 px-3 py-3"><option value="FULL">Full</option><option value="LOCAL">Local</option></select></label></div>
   <div className="grid sm:grid-cols-3 gap-3"><label className="text-xs font-bold">Preço de venda / un.<input type="number" step=".01" value={draft.salePriceUnit} onChange={e=>setDraft({...draft,salePriceUnit:num(e.target.value)})} className="mt-1 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-3"/></label><label className="text-xs font-bold">Valor recebido TOTAL<input type="number" step=".01" value={draft.receivedAmount} onChange={e=>setDraft({...draft,receivedAmount:num(e.target.value)})} className="mt-1 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-3"/></label><label className="text-xs font-bold">Custos extras TOTAL<input type="number" step=".01" value={draft.extraCosts} onChange={e=>setDraft({...draft,extraCosts:num(e.target.value)})} className="mt-1 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-3"/></label></div>
   <label className="text-xs font-bold block">Observação<input value={draft.note||''} onChange={e=>setDraft({...draft,note:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-3"/></label>
   <div className="rounded-xl bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-900 p-3 text-xs"><b>Preço de venda</b> = quanto o cliente pagou. <b>Valor recebido</b> = quanto efetivamente ficou para você após as deduções que já vieram descontadas. O lucro usa Recebido − CMV − Custos extras.</div>
   <button disabled={saving||!draft.inventoryId} onClick={submit} className="w-full bg-amber-400 text-slate-950 font-black rounded-xl py-3 disabled:opacity-50">{saving?'Salvando...':'Salvar venda'}</button>
  </div></div></div>}
 </div>
}