import React,{useEffect,useMemo,useState}from'react';
import{FinancePlan,CashEntry,DebtRecord}from'../types';
import{Wallet,CreditCard,Building2,User,AlertTriangle,Plus,X,Trash2,Settings2,Landmark,ArrowRight}from'lucide-react';

const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const today=()=>new Date().toISOString().slice(0,10);
type Tab='GERAL'|'EMPRESA'|'PESSOAL'|'MOVIMENTACOES';

const AllocationBar=({title,subtitle,base,items,onChange}:{title:string;subtitle:string;base:number;items:{key:string;label:string;value:number}[];onChange:(key:string,value:number)=>void})=>{
 const total=items.reduce((a,x)=>a+x.value,0);
 return <section className="space-y-4">
  <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-2"><div><h2 className="font-black">{title}</h2><p className="text-xs text-slate-500">{subtitle}</p></div><span className={`text-xs font-black px-3 py-1.5 rounded-full ${total===100?'bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-400':'bg-amber-100 text-amber-700 dark:bg-amber-950/40 dark:text-amber-400'}`}>{total}% de 100% {total===100?'✓':`• ajuste ${Math.abs(100-total)}%`}</span></div>
  <div className={`grid gap-3 ${items.length===5?'grid-cols-1 sm:grid-cols-2 lg:grid-cols-5':'grid-cols-1 sm:grid-cols-2 lg:grid-cols-4'}`}>{items.map((x,i)=>{const amount=base*x.value/100,r=45,c=2*Math.PI*r,d=c*x.value/100;return <div key={x.key} className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-4 text-center"><div className="flex justify-between gap-2 text-left"><b className="text-sm">{x.label}</b><span className="text-xs font-black text-amber-600">{x.value}%</span></div><div className="relative w-32 h-32 mx-auto my-3"><svg viewBox="0 0 120 120" className="w-full h-full -rotate-90"><circle cx="60" cy="60" r={r} fill="none" stroke="currentColor" strokeWidth="10" className="text-slate-100 dark:text-slate-800"/><circle cx="60" cy="60" r={r} fill="none" stroke="currentColor" strokeWidth="10" strokeLinecap="round" strokeDasharray={`${d} ${c-d}`} className="text-amber-400"/></svg><div className="absolute inset-0 flex flex-col justify-center items-center"><b>{base>0?money(amount):'R$ 0'}</b><span className="text-[10px] text-slate-500">destinados</span></div></div><label className="text-xs font-bold text-left block">Porcentagem<div className="flex gap-2 mt-2 items-center"><input type="range" min="0" max="100" value={x.value} onChange={e=>onChange(x.key,Number(e.target.value))} className="flex-1 accent-amber-400"/><input type="number" min="0" max="100" value={x.value} onChange={e=>onChange(x.key,Math.max(0,Math.min(100,Number(e.target.value)||0)))} className="w-16 p-2 rounded-lg border dark:border-slate-700 bg-transparent text-center font-bold"/></div></label></div>})}</div>
 </section>
};

export const FinanceCenterView:React.FC<{plan:FinancePlan;entries:CashEntry[];debts:DebtRecord[];onPlan:(p:FinancePlan)=>Promise<void>;onEntry:(x:any)=>Promise<void>;onDeleteEntry:(id:string)=>Promise<void>;onDebt:(x:any)=>Promise<void>;onDeleteDebt:(id:string)=>Promise<void>;onTransfer?:(direction:'BUSINESS_TO_PERSONAL'|'PERSONAL_TO_BUSINESS',amount:number,date:string,note:string)=>Promise<void>}>=({plan,entries,debts,onPlan,onEntry,onDeleteEntry,onDebt,onDeleteDebt,onTransfer})=>{
 const[p,setP]=useState(plan),[tab,setTab]=useState<Tab>('GERAL'),[entry,setEntry]=useState(false),[debt,setDebt]=useState(false),[transfer,setTransfer]=useState(false),[saving,setSaving]=useState(false);
 useEffect(()=>setP(plan),[plan]);
 const month=entries.filter(x=>x.date.slice(0,7)===today().slice(0,7));
 const businessIncome=month.filter(x=>x.area==='BUSINESS'&&x.kind==='INCOME').reduce((a,x)=>a+x.amount,0);
 const businessOut=month.filter(x=>x.area==='BUSINESS'&&x.kind!=='INCOME').reduce((a,x)=>a+x.amount,0);
 const businessAvailable=Math.max(0,businessIncome-businessOut);
 const personalIncome=month.filter(x=>x.area==='PERSONAL'&&x.kind==='INCOME').reduce((a,x)=>a+x.amount,0);
 const personalSpend=month.filter(x=>x.area==='PERSONAL'&&x.kind==='EXPENSE').reduce((a,x)=>a+x.amount,0);
 const debtPaid=month.filter(x=>x.area==='PERSONAL'&&x.kind==='DEBT_PAYMENT').reduce((a,x)=>a+x.amount,0);
 const debtTotal=debts.reduce((a,x)=>a+x.balance,0);
 const spendPct=(p.personalEssentialPct??p.personalSpendPct)+(p.personalFreePct??0);
 const spendLimit=personalIncome*spendPct/100;
 const status=spendLimit>0&&personalSpend>spendLimit?'VERMELHO':spendLimit>0&&personalSpend>spendLimit*.8?'AMARELO':'VERDE';
 const businessItems=[
  {key:'businessReinvestPct',label:'Reposição / Reinvestimento',value:p.businessReinvestPct??70},
  {key:'businessReservePct',label:'Reserva da empresa',value:p.businessReservePct??15},
  {key:'businessWithdrawalPct',label:'Retirada pessoal',value:p.businessWithdrawalPct??10},
  {key:'businessOtherPct',label:'Outros',value:p.businessOtherPct??5},
 ];
 const personalItems=[
  {key:'personalEssentialPct',label:'Gastos essenciais',value:p.personalEssentialPct??40},
  {key:'debtPct',label:'Dívidas',value:p.debtPct??25},
  {key:'personalFreePct',label:'Gastos livres',value:p.personalFreePct??10},
  {key:'reservePct',label:'Reserva',value:p.reservePct??15},
  {key:'investPct',label:'Investimentos',value:p.investPct??10},
 ];
 const change=(key:string,value:number)=>setP({...p,[key]:value});
 const save=async()=>{const bt=businessItems.reduce((a,x)=>a+(x.key in p?(p as any)[x.key]:x.value),0),pt=personalItems.reduce((a,x)=>a+(x.key in p?(p as any)[x.key]:x.value),0);if(bt!==100||pt!==100){alert('As distribuições Empresa e Pessoal precisam fechar exatamente 100%.');return}setSaving(true);try{await onPlan({...p,personalSpendPct:(p.personalEssentialPct??40)+(p.personalFreePct??10)})}finally{setSaving(false)}};
 return <div className="space-y-5 max-w-[1450px] mx-auto">
  <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><h1 className="text-2xl font-black">Centro Financeiro</h1><p className="text-sm text-slate-500">Empresa e pessoal separados, simples de acompanhar.</p></div><button onClick={()=>setTransfer(true)} className="bg-amber-400 text-slate-950 font-black px-4 py-2.5 rounded-xl text-xs">⇄ Transferir entre caixas</button></div>
  <div className="flex gap-2 overflow-x-auto pb-1">{[['GERAL','Visão Geral'],['EMPRESA','Empresa / ML'],['PESSOAL','Pessoal'],['MOVIMENTACOES','Movimentações']].map(([x,l])=><button key={x} onClick={()=>setTab(x as Tab)} className={`whitespace-nowrap px-4 py-2 rounded-xl text-xs font-black ${tab===x?'bg-amber-400 text-slate-950':'bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800'}`}>{l}</button>)}</div>

  {tab==='GERAL'&&<>
   <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Mercado Pago',p.mercadoPagoBalance,Building2],['Caixa empresa',p.businessCash,Wallet],['Caixa pessoal',p.personalCash,User],['Dívidas',debtTotal,CreditCard]].map(([l,v,I]:any)=><div className="p-4 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800" key={l}><div className="text-xs text-slate-500 font-bold flex gap-2"><I className="w-4 h-4"/>{l}</div><div className="text-xl font-black mt-2">{money(v)}</div></div>)}</div>
   <div className={`rounded-2xl border p-4 ${status==='VERMELHO'?'border-rose-400 bg-rose-50 dark:bg-rose-950/20':status==='AMARELO'?'border-amber-400 bg-amber-50 dark:bg-amber-950/20':'border-emerald-400 bg-emerald-50 dark:bg-emerald-950/20'}`}><div className="flex items-center gap-2 font-black"><AlertTriangle className="w-5 h-5"/>Semáforo: {status==='VERDE'?'SAUDÁVEL':status==='AMARELO'?'ATENÇÃO':'LIMITE ULTRAPASSADO'}</div><p className="text-xs mt-1 text-slate-600 dark:text-slate-400">Gastos pessoais: {money(personalSpend)} de {money(spendLimit)} planejados para essenciais + gastos livres.</p></div>
   <div className="grid lg:grid-cols-3 gap-3"><div className="p-4 rounded-2xl bg-white dark:bg-slate-900 border dark:border-slate-800"><b className="text-xs text-slate-500">Empresa disponível no mês</b><div className="text-xl font-black mt-2">{money(businessAvailable)}</div></div><div className="p-4 rounded-2xl bg-white dark:bg-slate-900 border dark:border-slate-800"><b className="text-xs text-slate-500">Renda pessoal do mês</b><div className="text-xl font-black mt-2">{money(personalIncome)}</div></div><div className="p-4 rounded-2xl bg-white dark:bg-slate-900 border dark:border-slate-800"><b className="text-xs text-slate-500">Dívidas pagas no mês</b><div className="text-xl font-black mt-2">{money(debtPaid)}</div></div></div>
  </>}

  {(tab==='GERAL'||tab==='EMPRESA')&&<AllocationBar title="Operação Mercado Livre" subtitle="Defina a porcentagem de cada círculo. O total deve fechar 100%." base={businessAvailable} items={businessItems} onChange={change}/>}
  {(tab==='GERAL'||tab==='PESSOAL')&&<AllocationBar title="Finança Pessoal" subtitle="Defina a porcentagem de cada círculo. O total deve fechar 100%." base={personalIncome} items={personalItems} onChange={change}/>}

  {(tab==='GERAL'||tab==='EMPRESA'||tab==='PESSOAL')&&<section className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-5"><div className="flex items-center gap-2"><Landmark className="w-5 h-5 text-amber-500"/><h2 className="font-black">Saldos</h2></div><p className="text-xs text-slate-500 mt-1">Saldos em reais não fazem parte das barras de 100%.</p><div className="grid sm:grid-cols-3 gap-3 mt-4"><label className="text-xs font-bold">Mercado Pago<input type="number" value={p.mercadoPagoBalance} onChange={e=>setP({...p,mercadoPagoBalance:Number(e.target.value)||0})} className="mt-1 w-full p-3 rounded-xl border dark:border-slate-700 bg-transparent"/></label><label className="text-xs font-bold">Caixa empresa<input type="number" value={p.businessCash} onChange={e=>setP({...p,businessCash:Number(e.target.value)||0})} className="mt-1 w-full p-3 rounded-xl border dark:border-slate-700 bg-transparent"/></label><label className="text-xs font-bold">Caixa pessoal<input type="number" value={p.personalCash} onChange={e=>setP({...p,personalCash:Number(e.target.value)||0})} className="mt-1 w-full p-3 rounded-xl border dark:border-slate-700 bg-transparent"/></label></div><button disabled={saving} onClick={save} className="mt-4 bg-amber-400 text-slate-950 font-black px-5 py-2.5 rounded-xl disabled:opacity-50">{saving?'Salvando...':'Salvar planejamento'}</button></section>}


  {tab==='MOVIMENTACOES'&&<section className="rounded-2xl bg-white dark:bg-slate-900 border dark:border-slate-800 overflow-hidden"><div className="p-4 flex justify-between"><div><h2 className="font-black">Movimentações financeiras</h2><p className="text-xs text-slate-500">Entradas, gastos, investimentos e pagamentos.</p></div><button onClick={()=>setEntry(true)} className="bg-amber-400 text-slate-950 font-black px-3 py-2 rounded-xl text-xs"><Plus className="inline w-4 h-4"/> Lançar</button></div>{entries.map(e=><div key={e.id} className="p-4 border-t dark:border-slate-800 grid grid-cols-[1fr_auto]"><div><b>{e.description}</b><p className="text-xs text-slate-500">{e.area==='BUSINESS'?'Empresa':'Pessoal'} • {e.category} • {new Date(e.date+'T12:00').toLocaleDateString('pt-BR')}</p></div><div className="flex gap-3 items-center"><b>{money(e.amount)}</b><button onClick={()=>onDeleteEntry(e.id)} className="text-rose-500"><Trash2 className="w-4 h-4"/></button></div></div>)}</section>}
  {transfer&&<TransferModal close={()=>setTransfer(false)} save={async(d:any)=>{if(onTransfer)await onTransfer(d.direction,d.amount,d.date,d.note);setTransfer(false)}} business={p.businessCash} personal={p.personalCash}/>}{entry&&<EntryModal close={()=>setEntry(false)} save={async(x:any)=>{await onEntry(x);setEntry(false)}}/>}
  {debt&&<DebtModal close={()=>setDebt(false)} save={async(x:any)=>{await onDebt(x);setDebt(false)}}/>}
 </div>
};

const EntryModal=({close,save}:any)=>{const[x,setX]=useState({area:'PERSONAL',kind:'EXPENSE',category:'Geral',description:'',amount:0,date:today()});return <div className="fixed inset-0 z-[100] bg-slate-950/70 grid place-items-center p-3"><div className="w-full max-w-md bg-white dark:bg-slate-900 rounded-2xl p-5 space-y-3"><div className="flex justify-between"><b>Novo lançamento</b><button onClick={close}><X/></button></div><div className="grid grid-cols-2 gap-2"><select value={x.area} onChange={e=>setX({...x,area:e.target.value})} className="p-3 rounded-xl border dark:border-slate-700 bg-white dark:bg-slate-900"><option value="PERSONAL">Pessoal</option><option value="BUSINESS">Empresa</option></select><select value={x.kind} onChange={e=>setX({...x,kind:e.target.value})} className="p-3 rounded-xl border dark:border-slate-700 bg-white dark:bg-slate-900"><option value="INCOME">Entrada</option><option value="EXPENSE">Gasto</option><option value="INVESTMENT">Investimento</option><option value="DEBT_PAYMENT">Pagamento dívida</option></select></div><input placeholder="Descrição" value={x.description} onChange={e=>setX({...x,description:e.target.value})} className="w-full p-3 rounded-xl border dark:border-slate-700 bg-transparent"/><input placeholder="Categoria" value={x.category} onChange={e=>setX({...x,category:e.target.value})} className="w-full p-3 rounded-xl border dark:border-slate-700 bg-transparent"/><div className="grid grid-cols-2 gap-2"><input type="number" placeholder="Valor" onChange={e=>setX({...x,amount:Number(e.target.value)||0})} className="p-3 rounded-xl border dark:border-slate-700 bg-transparent"/><input type="date" value={x.date} onChange={e=>setX({...x,date:e.target.value})} className="p-3 rounded-xl border dark:border-slate-700 bg-transparent"/></div><button onClick={()=>save(x)} className="w-full bg-amber-400 text-slate-950 font-black py-3 rounded-xl">Salvar</button></div></div>};

const DebtModal=({close,save}:any)=>{const[x,setX]=useState({name:'',balance:0,installment:0,dueDay:1,note:''});return <div className="fixed inset-0 z-[100] bg-slate-950/70 grid place-items-center p-3"><div className="w-full max-w-md bg-white dark:bg-slate-900 rounded-2xl p-5 space-y-3"><div className="flex justify-between"><b>Cadastrar dívida</b><button onClick={close}><X/></button></div><input placeholder="Credor / nome da dívida" onChange={e=>setX({...x,name:e.target.value})} className="w-full p-3 rounded-xl border dark:border-slate-700 bg-transparent"/><div className="grid grid-cols-2 gap-2"><input type="number" placeholder="Saldo devedor" onChange={e=>setX({...x,balance:Number(e.target.value)||0})} className="p-3 rounded-xl border dark:border-slate-700 bg-transparent"/><input type="number" placeholder="Parcela" onChange={e=>setX({...x,installment:Number(e.target.value)||0})} className="p-3 rounded-xl border dark:border-slate-700 bg-transparent"/></div><input type="number" min="1" max="31" placeholder="Dia vencimento" onChange={e=>setX({...x,dueDay:Number(e.target.value)||1})} className="w-full p-3 rounded-xl border dark:border-slate-700 bg-transparent"/><button onClick={()=>save(x)} className="w-full bg-amber-400 text-slate-950 font-black py-3 rounded-xl">Salvar dívida</button></div></div>};

const TransferModal=({close,save,business,personal}:any)=>{const[x,setX]=useState({direction:'BUSINESS_TO_PERSONAL',amount:0,date:today(),note:''});const from=x.direction==='BUSINESS_TO_PERSONAL'?business:personal;return <div className="fixed inset-0 z-[110] bg-slate-950/70 grid place-items-center p-3"><div className="w-full max-w-md bg-white dark:bg-slate-900 rounded-2xl p-5 space-y-3"><div className="flex justify-between"><div><b>Transferir dinheiro</b><p className="text-xs text-slate-500">Entre Operação ML e Finança Pessoal.</p></div><button onClick={close}><X/></button></div><select value={x.direction} onChange={e=>setX({...x,direction:e.target.value})} className="w-full p-3 rounded-xl border dark:border-slate-700 bg-white dark:bg-slate-900"><option value="BUSINESS_TO_PERSONAL">Operação ML → Pessoal (retirada)</option><option value="PERSONAL_TO_BUSINESS">Pessoal → Operação ML (aporte)</option></select><input type="number" placeholder="Valor" onChange={e=>setX({...x,amount:Number(e.target.value)||0})} className="w-full p-3 rounded-xl border-2 border-amber-300 dark:border-amber-700 bg-transparent text-lg font-black"/><p className="text-xs text-slate-500">Disponível na origem: <b>{money(from)}</b></p><input placeholder="Observação (opcional)" value={x.note} onChange={e=>setX({...x,note:e.target.value})} className="w-full p-3 rounded-xl border dark:border-slate-700 bg-transparent"/><button disabled={!x.amount||x.amount>from} onClick={()=>save(x)} className="w-full bg-amber-400 text-slate-950 font-black py-3 rounded-xl disabled:opacity-40">Confirmar transferência</button></div></div>};
