import React,{useMemo,useState} from 'react';
import { SaleRecord,InventoryItem } from '../types';
import { DollarSign,Plus,TrendingUp,Coins,Percent,X,Pencil,Trash2,PackageCheck } from 'lucide-react';
type Draft=Partial<SaleRecord>&{inventoryId:string;quantity:number;source:'LOCAL'|'FULL';salePriceUnit:number;receivedAmount:number;soldAt:string;extraCosts:number};
const today=()=>new Date().toISOString().slice(0,10), money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export const FinanceView:React.FC<{sales:SaleRecord[];items:InventoryItem[];onSave:(d:Draft)=>Promise<void>;onDelete:(id:string)=>Promise<void>}>=({sales,items,onSave,onDelete})=>{
 const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[editSale,setEditSale]=useState<SaleRecord|null>(null),[del,setDel]=useState<SaleRecord|null>(null);
 const [draft,setDraft]=useState<Draft>({inventoryId:'',quantity:1,source:'FULL',salePriceUnit:0,receivedAmount:0,soldAt:today(),extraCosts:0});
 const st=useMemo(()=>{let received=0,cmv=0,units=0; sales.forEach(x=>{received+=x.receivedAmount;cmv+=x.cmv;units+=x.quantity});const profit=received-cmv;return{received,cmv,profit,margin:received?profit/received*100:0,units}},[sales]);
 const start=(x?:SaleRecord)=>{setEditSale(x||null);setDraft(x?{...x}:{inventoryId:items[0]?.id||'',quantity:1,source:'FULL',salePriceUnit:0,receivedAmount:0,soldAt:today(),extraCosts:0});setOpen(true)};
 const submit=async()=>{setSaving(true);try{await onSave({...draft,id:editSale?.id,extraCosts:0});setOpen(false)}finally{setSaving(false)}};
 return <div className="space-y-5 max-w-[1400px] mx-auto">
  <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><h1 className="text-2xl font-black flex items-center gap-2"><DollarSign className="text-amber-500"/>Financeiro & Vendas</h1><p className="text-sm text-slate-500">Simples: informe quanto recebeu. O custo vem automaticamente do SKU.</p></div><button onClick={()=>start()} disabled={!items.length} className="bg-amber-400 text-slate-950 font-black rounded-xl px-4 py-2.5 flex items-center gap-2 disabled:opacity-50"><Plus className="w-4 h-4"/>Nova venda</button></div>
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[['Recebido',money(st.received),Coins],['Custo produtos',money(st.cmv),PackageCheck],['Lucro',money(st.profit),TrendingUp],['Margem',st.margin.toFixed(1)+'%',Percent],['Unidades vendidas',st.units,PackageCheck]].map(([l,v,I]:any)=><div key={l} className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-4"><div className="text-xs uppercase font-bold text-slate-500 flex gap-2"><I className="w-4 h-4"/>{l}</div><div className="text-xl font-black mt-2">{v}</div></div>)}</div>
  <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden"><div className="p-4 border-b border-slate-200 dark:border-slate-800"><b>Todas as vendas</b><p className="text-xs text-slate-500">Recebido − custo do produto = lucro.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-xs"><thead className="bg-slate-50 dark:bg-slate-800"><tr>{['Data','SKU / Produto','Qtd.','Recebido','Custo','Lucro','Margem',''].map(x=><th className="p-3 text-left uppercase" key={x}>{x}</th>)}</tr></thead><tbody>{sales.map(x=>{const profit=x.receivedAmount-x.cmv,margin=x.receivedAmount?profit/x.receivedAmount*100:0;return <tr className="border-t border-slate-100 dark:border-slate-800" key={x.id}><td className="p-3">{new Date(x.soldAt+'T12:00').toLocaleDateString('pt-BR')}</td><td className="p-3"><b className="text-amber-600">{x.sku}</b><div>{x.productName}</div></td><td className="p-3">{x.quantity}</td><td className="p-3 font-bold">{money(x.receivedAmount)}</td><td className="p-3">{money(x.cmv)}</td><td className={`p-3 font-black ${profit>=0?'text-emerald-600':'text-rose-600'}`}>{money(profit)}</td><td className="p-3 font-bold">{margin.toFixed(1)}%</td><td className="p-3"><button onClick={()=>start(x)} className="p-2"><Pencil className="w-4 h-4"/></button><button onClick={()=>setDel(x)} className="p-2 text-rose-500"><Trash2 className="w-4 h-4"/></button></td></tr>})}</tbody></table>{!sales.length&&<div className="p-10 text-center text-slate-500">Nenhuma venda cadastrada.</div>}</div></div>
  {open&&<div className="fixed inset-0 z-[90] bg-slate-950/70 p-3 grid place-items-center"><div className="w-full max-w-xl bg-white dark:bg-slate-900 rounded-2xl border dark:border-slate-800 p-5 space-y-4"><div className="flex justify-between"><div><h2 className="font-black">{editSale?'Editar venda':'Nova venda'}</h2><p className="text-xs text-slate-500">Sem taxas e fretes: use o valor líquido que você recebeu.</p></div><button onClick={()=>setOpen(false)}><X/></button></div><label className="text-xs font-bold block">SKU<select value={draft.inventoryId} onChange={e=>setDraft({...draft,inventoryId:e.target.value})} className="mt-1 w-full p-3 rounded-xl border dark:border-slate-700 bg-white dark:bg-slate-900">{items.map(i=><option key={i.id} value={i.id}>{i.sku} — {i.name} (custo {money(i.unitCost)})</option>)}</select></label><div className="grid grid-cols-3 gap-3"><label className="text-xs font-bold">Data<input type="date" value={draft.soldAt} onChange={e=>setDraft({...draft,soldAt:e.target.value})} className="mt-1 w-full p-3 rounded-xl border dark:border-slate-700 bg-transparent"/></label><label className="text-xs font-bold">Qtd.<input type="number" min="1" value={draft.quantity} onChange={e=>setDraft({...draft,quantity:Math.max(1,Number(e.target.value)||1)})} className="mt-1 w-full p-3 rounded-xl border dark:border-slate-700 bg-transparent"/></label><label className="text-xs font-bold">Origem<select value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value as any})} className="mt-1 w-full p-3 rounded-xl border dark:border-slate-700 bg-white dark:bg-slate-900"><option value="FULL">Full</option><option value="LOCAL">Local</option></select></label></div><label className="text-xs font-bold block">Quanto recebi pela venda (TOTAL)<input type="number" step=".01" value={draft.receivedAmount} onChange={e=>setDraft({...draft,receivedAmount:Math.max(0,Number(e.target.value)||0),salePriceUnit:(Math.max(0,Number(e.target.value)||0)/(draft.quantity||1))})} className="mt-1 w-full p-3 rounded-xl border-2 border-amber-300 dark:border-amber-700 bg-transparent text-lg font-black"/></label><button disabled={saving} onClick={submit} className="w-full py-3 rounded-xl bg-amber-400 text-slate-950 font-black">{saving?'Salvando...':'Salvar venda'}</button></div></div>}
  {del&&<div className="fixed inset-0 z-[100] bg-slate-950/60 backdrop-blur-sm p-4 flex items-center justify-center"><div className="max-w-md w-full bg-white dark:bg-slate-900 rounded-2xl border dark:border-slate-800 p-5"><h3 className="font-black">Excluir venda</h3><p className="text-sm text-slate-500 mt-2">O estoque de {del.quantity} unidade(s) será devolvido automaticamente.</p><div className="flex justify-end gap-2 mt-5"><button onClick={()=>setDel(null)} className="px-4 py-2 rounded-xl border dark:border-slate-700">Cancelar</button><button onClick={async()=>{await onDelete(del.id);setDel(null)}} className="px-4 py-2 rounded-xl bg-rose-600 text-white font-bold">Excluir</button></div></div></div>}
 </div>
}