import React, { useMemo, useState } from 'react';
import { Boxes, PackagePlus, Warehouse, Truck, Store, Pencil, Trash2, X, AlertTriangle, PackageCheck, Coins } from 'lucide-react';
import { InventoryItem } from '../types';

type Draft = Omit<InventoryItem,'id'|'createdAt'|'updatedAt'> & {id?:string};
const blank: Draft = {sku:'',name:'',unitCost:0,localStock:0,fullStock:0,supplierInbound:0,fullInbound:0,minStock:5};
const n=(v:string)=>Math.max(0,Number(v)||0);

export const InventoryView: React.FC<{items:InventoryItem[]; onSave:(d:Draft)=>Promise<void>; onDelete:(id:string)=>Promise<void>}> = ({items,onSave,onDelete}) => {
 const [draft,setDraft]=useState<Draft>(blank); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false);
 const stats=useMemo(()=>{const local=items.reduce((a,i)=>a+i.localStock,0),full=items.reduce((a,i)=>a+i.fullStock,0),supplier=items.reduce((a,i)=>a+i.supplierInbound,0),toFull=items.reduce((a,i)=>a+i.fullInbound,0); return {local,full,supplier,toFull,total:local+full+supplier+toFull,capital:items.reduce((a,i)=>a+(i.localStock+i.fullStock+i.supplierInbound+i.fullInbound)*i.unitCost,0),low:items.filter(i=>i.localStock+i.fullStock+i.supplierInbound+i.fullInbound<=i.minStock).length}},[items]);
 const edit=(i:InventoryItem)=>{setDraft({...i});setOpen(true)};
 const add=()=>{const next=`IMP-${String(items.length+1).padStart(4,'0')}`;setDraft({...blank,sku:next});setOpen(true)};
 const submit=async()=>{if(!draft.sku.trim()||!draft.name.trim())return;setSaving(true);try{await onSave({...draft,sku:draft.sku.trim().toUpperCase(),name:draft.name.trim()});setOpen(false);setDraft(blank)}finally{setSaving(false)}};
 return <div className="space-y-5 max-w-7xl mx-auto">
  <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><div className="flex items-center gap-2"><Warehouse className="w-6 h-6 text-amber-500"/><h1 className="text-xl sm:text-2xl font-black">Galpão IMPÉRIO</h1></div><p className="text-sm text-slate-500 dark:text-slate-400 mt-1">Controle visual de SKUs, estoque Local, Full e mercadorias em trânsito.</p></div><button onClick={add} className="flex items-center justify-center gap-2 bg-amber-400 hover:bg-amber-500 text-slate-950 font-black rounded-xl px-4 py-2.5 text-sm"><PackagePlus className="w-4 h-4"/>Cadastrar SKU</button></div>
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">
   {[['SKUs',items.length,Boxes],['Local',stats.local,Store],['Full',stats.full,PackageCheck],['Em trânsito',stats.supplier+stats.toFull,Truck],['Capital estoque',stats.capital.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),Coins]].map(([l,v,I]:any)=><div key={l} className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-4"><div className="flex items-center gap-2 text-slate-500 dark:text-slate-400 text-xs font-bold uppercase"><I className="w-4 h-4"/>{l}</div><div className="text-xl font-black mt-2">{v}</div></div>)}
  </div>
  {stats.low>0&&<div className="flex items-center gap-2 rounded-xl border border-amber-300 dark:border-amber-800 bg-amber-50 dark:bg-amber-950/30 p-3 text-sm font-bold"><AlertTriangle className="w-4 h-4 text-amber-600"/>{stats.low} SKU(s) no nível mínimo ou abaixo.</div>}
  <section className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-900 dark:bg-black overflow-hidden">
   <div className="px-4 py-3 border-b border-slate-700 flex items-center justify-between text-white"><div><p className="font-black text-sm">VISÃO DO GALPÃO</p><p className="text-xs text-slate-400">Cada box é um SKU. Quanto maior o estoque, mais cheio ele fica.</p></div><span className="text-xs bg-slate-800 px-2 py-1 rounded-lg">{stats.total} un.</span></div>
   <div className="p-4 grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4 bg-[linear-gradient(180deg,#111827,#0f172a)]">
    {items.length===0?<button onClick={add} className="min-h-44 border-2 border-dashed border-slate-700 rounded-xl text-slate-400 hover:border-amber-400 hover:text-amber-400 flex flex-col items-center justify-center gap-2"><PackagePlus className="w-7 h-7"/><span className="text-sm font-bold">Cadastrar primeiro SKU</span></button>:items.map(i=>{const owned=i.localStock+i.fullStock+i.supplierInbound+i.fullInbound;const capacity=Math.max(i.minStock*4,50);const fill=Math.min(100,Math.round(owned/capacity*100));return <div key={i.id} className="relative rounded-xl border border-slate-700 bg-slate-800/90 overflow-hidden">
      <div className="h-2 bg-slate-700"><div className="h-full bg-amber-400 transition-all" style={{width:`${fill}%`}}/></div>
      <div className="p-4"><div className="flex justify-between gap-2"><div className="min-w-0"><span className="text-2xs font-black text-amber-400 tracking-wider">{i.sku}</span><h3 className="text-white font-bold truncate">{i.name}</h3></div><div className="flex"><button onClick={()=>edit(i)} className="p-1.5 text-slate-400 hover:text-white"><Pencil className="w-4 h-4"/></button><button onClick={()=>confirm(`Excluir ${i.sku}?`)&&onDelete(i.id)} className="p-1.5 text-slate-400 hover:text-rose-400"><Trash2 className="w-4 h-4"/></button></div></div>
       <div className="mt-4 h-20 flex items-end gap-1.5 border-b-4 border-slate-600 px-1">{Array.from({length:10}).map((_,x)=><div key={x} className={`flex-1 rounded-t-sm border border-slate-600 ${x<Math.ceil(fill/10)?'bg-amber-400':'bg-slate-700/50'}`} style={{height:`${28+(x%3)*8}px`}}/>)}</div>
       <div className="grid grid-cols-2 gap-2 mt-3 text-xs"><div className="bg-slate-900 rounded-lg p-2"><span className="text-slate-400">Local</span><b className="block text-white text-base">{i.localStock}</b></div><div className="bg-slate-900 rounded-lg p-2"><span className="text-slate-400">Full</span><b className="block text-white text-base">{i.fullStock}</b></div><div className="bg-slate-900 rounded-lg p-2"><span className="text-slate-400">A receber</span><b className="block text-sky-300">{i.supplierInbound}</b></div><div className="bg-slate-900 rounded-lg p-2"><span className="text-slate-400">→ Full</span><b className="block text-emerald-300">{i.fullInbound}</b></div></div>
       <div className="mt-3 flex justify-between text-2xs text-slate-400"><span>Total empresa: <b className="text-white">{owned}</b></span><span>Mín.: {i.minStock}</span></div>
      </div></div>})}
   </div>
  </section>
  <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-hidden"><div className="px-4 py-3 border-b border-slate-200 dark:border-slate-800 font-black text-sm">Resumo dos SKUs</div><div className="divide-y divide-slate-100 dark:divide-slate-800">{items.map(i=><button key={i.id} onClick={()=>edit(i)} className="w-full p-4 text-left grid grid-cols-[1fr_auto] gap-3 hover:bg-slate-50 dark:hover:bg-slate-800/50"><div className="min-w-0"><div className="font-black text-xs text-amber-600">{i.sku}</div><div className="font-bold truncate">{i.name}</div></div><div className="text-right"><div className="font-black">{i.localStock+i.fullStock+i.supplierInbound+i.fullInbound} un.</div><div className="text-xs text-slate-500">Custo {i.unitCost.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</div></div></button>)}</div></div>
  {open&&<div className="fixed inset-0 z-[70] bg-slate-950/70 p-3 grid place-items-center"><div className="w-full max-w-2xl max-h-[92vh] overflow-y-auto rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800"><div className="sticky top-0 bg-white dark:bg-slate-900 px-5 py-4 border-b border-slate-200 dark:border-slate-800 flex justify-between"><div><h2 className="font-black">{draft.id?'Editar SKU':'Cadastrar SKU'}</h2><p className="text-xs text-slate-500">O estoque fica salvo no Firestore e aparece nos dois aparelhos.</p></div><button onClick={()=>setOpen(false)}><X className="w-5 h-5"/></button></div><div className="p-5 space-y-4">
   <div className="grid sm:grid-cols-2 gap-3"><label className="text-xs font-bold">SKU<input value={draft.sku} onChange={e=>setDraft({...draft,sku:e.target.value})} placeholder="IMP-0001" className="mt-1 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2.5 text-sm uppercase"/></label><label className="text-xs font-bold">Produto<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Ex.: Caneta iPad" className="mt-1 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2.5 text-sm"/></label></div>
   <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{[['Custo unitário','unitCost'],['Estoque mínimo','minStock'],['Estoque Local','localStock'],['Estoque Full','fullStock'],['A receber fornecedor','supplierInbound'],['Enviado ao Full','fullInbound']].map(([l,k])=><label key={k} className="text-xs font-bold">{l}<input type="number" min="0" step={k==='unitCost'?'0.01':'1'} value={(draft as any)[k]} onChange={e=>setDraft({...draft,[k]:n(e.target.value)})} className="mt-1 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2.5 text-sm"/></label>)}</div>
   <div className="rounded-xl bg-slate-50 dark:bg-slate-800 p-3 text-xs text-slate-600 dark:text-slate-300"><b>Em trânsito:</b> “A receber fornecedor” = comprado e ainda não chegou até você. “Enviado ao Full” = saiu do seu estoque local e aguarda entrada no Full.</div>
   <button disabled={saving||!draft.sku.trim()||!draft.name.trim()} onClick={submit} className="w-full rounded-xl bg-amber-400 disabled:opacity-50 text-slate-950 font-black py-3">{saving?'Salvando...':'Salvar SKU'}</button>
  </div></div></div>}
 </div>
}
